admin:
  size: "50x50"
  url: "default_avatar.jpg"
news:
  per_page: 2
image:
  max_capacity: 5 #MB
teams:
  per_page: 1
players:
  per_page: 3
per_page: 4
min_player_of_team: 2
team:
  logo_size_title: "70x70"
  logo_size_left: "50x50"
league_season:
  min_team_of_league: 4
number_of_year: 10
match:
  ball_size: "70x70"
  ball_img: "league-icon.png"
users:
  avatar_size: "200x200"
  avt_default: "default_avatar.jpg"
activity:
  logo_team: "30x30"
  per_page: 5
country:
  per_page: 4
  size_tiny: "40x20"
  size_small: "60x30"
